version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: postgres-fipe
    restart: always
    environment:
      POSTGRES_DB: fipe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
